# Generated by Django 3.1.12 on 2022-05-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=10)),
                ('program', models.CharField(max_length=25)),
                ('module', models.CharField(max_length=25)),
                ('students', models.IntegerField()),
                ('room', models.CharField(max_length=25)),
                ('date', models.CharField(max_length=25)),
                ('time', models.CharField(max_length=25)),
            ],
        ),
    ]
