# Generated by Django 3.2 on 2022-07-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduling', '0002_scheduling'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
