# Generated by Django 3.2 on 2022-07-02 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0011_session1'),
        ('Scheduling', '0003_timetable_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_timetable', to='Database.department'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_timetable', to='Database.program'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_allocations', to='Database.room'),
        ),
    ]
