# Generated by Django 3.2 on 2022-07-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduling', '0004_auto_20220702_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='room',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
