# Generated by Django 3.2 on 2022-07-11 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduling', '0005_alter_timetable_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='department',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='program',
        ),
    ]
