# Generated by Django 3.2 on 2022-07-11 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduling', '0006_auto_20220711_2030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeTable',
        ),
    ]
