# Generated by Django 3.2 on 2022-07-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduling', '0007_delete_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=10)),
                ('module', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=100, null=True)),
                ('students', models.IntegerField()),
                ('room', models.CharField(max_length=100, null=True)),
                ('date', models.CharField(max_length=25)),
                ('time', models.CharField(max_length=25)),
            ],
        ),
    ]
