# Generated by Django 3.2 on 2022-07-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduling', '0008_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='room',
            field=models.CharField(choices=[], max_length=100, null=True),
        ),
    ]
