# Generated by Django 3.2 on 2022-07-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduling', '0009_alter_timetable_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoneScheduling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_done', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='timetable',
            name='room',
            field=models.CharField(choices=[('LAB1', 'LAB1'), ('WKSHOP', 'WKSHOP'), ('LAB2', 'LAB2')], max_length=100, null=True),
        ),
    ]
