# Generated by Django 3.2 on 2022-07-22 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0012_alter_registration_students'),
        ('Scheduling', '0010_auto_20220721_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvigilatorAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invigilator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='allocated_dates', to='Database.invigilator')),
                ('slot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='slot_invigilator', to='Scheduling.timetable')),
            ],
        ),
    ]
