# Generated by Django 3.2 on 2022-07-22 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduling', '0011_invigilatorassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invigilatorassignment',
            name='slot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_invigilator', to='Scheduling.timetable'),
        ),
    ]
