# Generated by Django 3.1.12 on 2022-05-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='dept_id',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='module',
            name='numOfStudents',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='shared_programs',
            field=models.ManyToManyField(blank=True, null=True, related_name='shared_programs', to='Management.Program'),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('1.1', '1.1'), ('1.2', '1.2'), ('2.1', '2.1'), ('2.2', '2.2'), ('3.1', '3.1'), ('3.2', '3.2'), ('4.1', '4.1'), ('4.2', '4.2'), ('5.1', '5.1'), ('5.2', '5.2')], max_length=25),
        ),
    ]
