# Generated by Django 3.1 on 2022-06-18 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_auto_20220518_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invigilator',
            name='department',
        ),
        migrations.RemoveField(
            model_name='module',
            name='program',
        ),
        migrations.RemoveField(
            model_name='module',
            name='shared_programs',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='module',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='students',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.RemoveField(
            model_name='student',
            name='program',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Invigilator',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
