# Generated by Django 3.2 on 2022-07-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='access_level',
            field=models.CharField(choices=[('Admins', 'Admins'), ('Staff', 'Staff'), ('hod', 'hod')], max_length=100),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
