# Generated by Django 3.1.12 on 2022-06-30 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0011_session1'),
        ('Accounts', '0003_auto_20220630_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('ec_number', models.CharField(max_length=8)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='department_hod', to='Database.department')),
            ],
        ),
    ]
