# Generated by Django 3.1 on 2022-06-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='shared_programs',
            field=models.ManyToManyField(blank=True, null=True, related_name='shared_programmes', to='Database.Program'),
        ),
    ]
