# Generated by Django 3.1 on 2022-06-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0002_auto_20220618_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='shared_level',
            field=models.CharField(blank=True, choices=[('1.1', '1.1'), ('1.2', '1.2'), ('2.1', '2.1'), ('2.2', '2.2'), ('3.1', '3.1'), ('3.2', '3.2'), ('4.1', '4.1'), ('4.2', '4.2'), ('5.1', '5.1'), ('5.2', '5.2')], max_length=10, null=True),
        ),
    ]
