# Generated by Django 3.1 on 2022-06-18 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0004_module_borrowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='shared_level',
        ),
        migrations.RemoveField(
            model_name='module',
            name='shared_programs',
        ),
        migrations.CreateModel(
            name='SharedPrograms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_level', models.CharField(blank=True, choices=[('1.1', '1.1'), ('1.2', '1.2'), ('2.1', '2.1'), ('2.2', '2.2'), ('3.1', '3.1'), ('3.2', '3.2'), ('4.1', '4.1'), ('4.2', '4.2'), ('5.1', '5.1'), ('5.2', '5.2')], max_length=10, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_programs', to='Database.module')),
                ('shared_programs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_programmes', to='Database.program')),
            ],
        ),
    ]
