# Generated by Django 3.1 on 2022-06-28 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0005_auto_20220618_1850'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
