# Generated by Django 3.1 on 2022-06-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0007_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
