# Generated by Django 3.1 on 2022-06-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0010_auto_20220628_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=25, null=True)),
                ('date', models.DateField(null=True)),
                ('time', models.CharField(max_length=100)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
            ],
        ),
    ]
